using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Turret : MonoBehaviour
{

    public GameObject bullet;

    public float rangeToTargetPlayer, timeBetweenShots = 0f;
    private float shotCounter;

    public Transform gun, firepoint;

    public float rotateSpeed = 5f;

    // Start is called before the first frame update
    void Start()
    {
        shotCounter = timeBetweenShots;
    }

    // Update is called once per frame
    void Update()
    {
        if (Vector3.Distance(transform.position, playerController.instance.transform.position)<rangeToTargetPlayer)
        {
            gun.LookAt(playerController.instance.transform.position + new Vector3(0f,.1f,0f));

            shotCounter -= Time.deltaTime;

            if (shotCounter <= 0)
            {
                Instantiate(bullet, firepoint.position, firepoint.rotation);
                shotCounter = timeBetweenShots;
            }
       
        }     else
            {
                shotCounter = timeBetweenShots;
                gun.rotation = Quaternion.Lerp(gun.rotation, Quaternion.Euler(0f, gun.rotation.eulerAngles.y + 10f, 0f), rotateSpeed * Time.deltaTime);
            }
    }
}
